-- MySQL Script generated by MySQL Workbench
-- Wed Jun  5 22:17:38 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema estoque
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema estoque
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `estoque` DEFAULT CHARACTER SET utf8 ;
USE `estoque` ;

-- -----------------------------------------------------
-- Table `estoque`.`Estoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`Estoque` (
  `idEstoque` INT NOT NULL AUTO_INCREMENT,
  `quantEstoque` INT NOT NULL,
  PRIMARY KEY (`idEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estoque`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`Produto` (
  `idProduto` INT NOT NULL AUTO_INCREMENT,
  `nomeProduto` VARCHAR(45) NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`idProduto`),
  INDEX `fk_Produto_Estoque_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Produto_Estoque`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `estoque`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estoque`.`Filial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`Filial` (
  `idFilial` INT NOT NULL AUTO_INCREMENT,
  `local` VARCHAR(45) NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`idFilial`),
  INDEX `fk_Filial_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Filial_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `estoque`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estoque`.`SolicitarEstoque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`SolicitarEstoque` (
  `idSolicitarEstoque` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `quantSolictado` INT NOT NULL,
  PRIMARY KEY (`idSolicitarEstoque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `estoque`.`Itens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `estoque`.`Itens` (
  `idItens` INT NOT NULL AUTO_INCREMENT,
  `SolicitarEstoque_idSolicitarEstoque` INT NOT NULL,
  `Estoque_idEstoque` INT NOT NULL,
  PRIMARY KEY (`idItens`, `SolicitarEstoque_idSolicitarEstoque`, `Estoque_idEstoque`),
  INDEX `fk_Itens_SolicitarEstoque1_idx` (`SolicitarEstoque_idSolicitarEstoque` ASC) VISIBLE,
  INDEX `fk_Itens_Estoque1_idx` (`Estoque_idEstoque` ASC) VISIBLE,
  CONSTRAINT `fk_Itens_SolicitarEstoque1`
    FOREIGN KEY (`SolicitarEstoque_idSolicitarEstoque`)
    REFERENCES `estoque`.`SolicitarEstoque` (`idSolicitarEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Itens_Estoque1`
    FOREIGN KEY (`Estoque_idEstoque`)
    REFERENCES `estoque`.`Estoque` (`idEstoque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
